// shaders/raytrace.comp
#version 430 core

layout(local_size_x = 16, local_size_y = 16) in;
layout(rgba32f, binding = 0) uniform image2D outputImage;
uniform sampler2D u_input;

uniform float u_r;           // sphere radius
uniform float u_n;           // refractive index
uniform float u_a;           // source plane distance
uniform float u_b;           // screen distance
uniform vec2  u_resolution;

const float screenSize = 1.0;
const float fov = 0.0; //todo neimplementirano/neuporabno

void main() {

    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    vec2 uv = vec2(coord) / u_resolution;
    // sample input with filtering — uv is [0,1] across the image
    vec4 inputColor = texture(u_input, uv);


    vec3 color_accumulator = vec3(1.0, 0.0, 0.0);

    //---------------------------------------------------------------------------------------------
    //cast ray
    //---------------------------------------------------------------------------------------------

    vec3 k = vec3(0.0, 0.0, 1.0);
    vec3 origin = vec3(0.0 + uv.x, 0.0 + uv.y, 0.0);
    float t = 0;
    vec3 ray = k * t + origin;

    //---------------------------------------------------------------------------------------------
    //ray tracing
    //---------------------------------------------------------------------------------------------



    //---------------------------------------------------------------------------------------------
    //light interaction on air/glass boundry
    //---------------------------------------------------------------------------------------------

    //---------------------------------------------------------------------------------------------
    //hits image
    //---------------------------------------------------------------------------------------------


    //accumulate color
    imageStore(outputImage, coord, vec4(inputColor));
}